### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by PetitPotiron** [discord-bugcenter/HelpCenter#82]
**Is your feature request related to a problem? Please describe.**
When we are contributing to the project, we do not contribute to the hacktoberfest.

**Describe the solution you'd like**
Add the 'hacktoberfest' and 'hacktoberfest2021' topics to the repo.

**Describe alternatives you've considered**
No alternative

**Comment by n1c00o** [comment]
Done.
But if we start to get bots, I will remove it
