### ISSUE TITLE
Redone database tag

### ISSUE THREAD

**Issue by icecodder** [discord-bugcenter/HelpCenter#88]
The database tag contains many errors, it should be redone (I'll do it soon). For example NoSQL means `Not only SQL` and not `no SQL`, also, NoSQL databases are not necessarily unstructured, there are some that are structured (in fact they are semi-structured).
![image](https://user-images.githubusercontent.com/47574874/137601527-1ee38fe8-bff2-41a0-9682-acee90de46fc.png)
There is an excellent article [here](https://towardsdatascience.com/datastore-choices-sql-vs-nosql-database-ebec24d56106)

**Comment by maxchrr** [comment]
Moved to [bugcenter/tags](https://github.com/discord-bugcenter/tags)
